### ISSUE TITLE
安卓安装apk，打开后只显示一张图片

### ISSUE THREAD

**Issue by chxybin** [evilbinary/scheme-lib#19]
环境：vivo funtouch os 2.6
           android 6.0
打开应用后只显示一张图片（http://evilbinary.org/static/img/g2.jpg ）
并偶尔提示“无法连接网络”。（网络本身没有问题，开流量，而且应用本身需要网络？？）
可以直接返回或home，没有发生卡顿。

**Comment by evilbinary** [comment]
本身需要登录，登录后就不需要了。

**Comment by evilbinary** [comment]
@chxybin 你从哪里登录的？

**Comment by evilbinary** [comment]
@chclock ch 方便截图看看么。
