### ISSUE TITLE
Runtime issues (Ubuntu 18.04)

### ISSUE THREAD

**Issue by paines** [evilbinary/scheme-lib#22]
After compiling, and installing the specific ChezScheme Version 9.5.1 with t6ale machine option, your scheme executable failes with 
```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:bin/  bin/scheme 
Error in $install-library-entry: invalid index ~s
(524)
```

Also i have sawn the issue that I get a floatin point excetion coming from Chez on startup during your scheme executable. Chez itself runs fine.

**Comment by evilbinary** [comment]
It should be environment problem.
Have you exec  `source ./env.sh` cmd?

**Comment by paines** [comment]
Oh I am so sorry, I missed that. I should learn some chinese ;)

Thank you very much!

**Comment by evilbinary** [comment]
Aha! Yep, you should learn some chinese.
