### ISSUE TITLE
(scheme-lib Version 1.5) Application Crashed click on login

### ISSUE THREAD

**Issue by waqaranwar888** [evilbinary/scheme-lib#28]
#### Project Information

* Repository: https://github.com/evilbinary/scheme-lib

* Project Name: scheme-lib

* My GitHub Account : https://github.com/waqaranwar888

#### Expected behavior
when i click on login . it's logged in my account 

#### Actual behavior
when i click on login for logging my account application crashed

#### How to reproduce

1-download scheme
2-add user name and password 
3-click on login 
4- application crashed

* Browser/App version: 1.5
* Operating system: 6.0.1

#### Recording Of The Bug
![20190720_153549](https://user-images.githubusercontent.com/52924148/61577774-95ec7a80-ab05-11e9-8e92-a42da2ad5b5a.gif)

# Logcat 

<pre><code>07-20 15:51:50.033 26533 26533 D AndroidRuntime: Shutting down VM

07-20 15:51:50.033 26533 26533 E AndroidRuntime: FATAL EXCEPTION: main

07-20 15:51:50.033 26533 26533 E AndroidRuntime: Process: org.evilbinary.chez, PID: 26533

07-20 15:51:50.033 26533 26533 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.evilbinary.chez.modle.Result.isSuccess()' on a null object reference

07-20 15:51:50.033 26533 26533 E AndroidRuntime: 	at org.evilbinary.chez.activity.f.a(LoginActivity.java:104)

07-20 15:51:50.033 26533 26533 E AndroidRuntime: 	at org.evilbinary.chez.activity.f.a(LoginActivity.java:101)

07-20 15:51:50.033 26533 26533 E AndroidRuntime: 	at org.evilbinary.a.a.a.b(BaseRequest.java:167)

07-20 15:51:50.033 26533 26533 E AndroidRuntime: 	at com.android.volley.h.run(ExecutorDelivery.java:101)

07-20 15:51:50.033 26533 26533 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

07-20 15:51:50.033 26533 26533 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

07-20 15:51:50.033 26533 26533 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

07-20 15:51:50.033 26533 26533 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7406)

07-20 15:51:50.033 26533 26533 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

07-20 15:51:50.033 26533 26533 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

07-20 15:51:50.033 26533 26533 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
</code></pre>

**Comment by evilbinary** [comment]
It's seem that you network canno be connect to api server ,Sorry i found api sever has down.

**Comment by waqaranwar888** [comment]
can you please guide me . how to connect api server. because i am new here. and zero knowledge of programming

**Comment by evilbinary** [comment]
just open it in browser

**Comment by evilbinary** [comment]
Hi, if you have no any question ,i just gonna to close this issue.
