### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by gassechen** [evilbinary/scheme-lib#37]
Hello. Not load apps scheme in android apk.
Thanks

**Comment by gassechen** [comment]
this error try compile for linux64 

main.c:33:34: note: expected ‘char **’ but argument is of type ‘const char **’
   33 | void process_arg(int argc,char * argv[]){
      |                           ~~~~~~~^~~~~~
cc  -Wall -Wformat -I../libscm -g   main.o  -o scheme   -L../libscm -lscm -lm -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/ -ldl -lrt -lpthread -luuid -llz4 -L/usr/lib/x86_64-linux-gnu/
/usr/bin/ld: cannot find -llz4
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:64: scheme] Error 1
make[2]: Leaving directory '/home/SCHEME/scheme-lib/lib/scheme'
make[1]: *** [Makefile:55: scheme/scheme] Error 2
make[1]: Leaving directory '/home/SCHEME/scheme-lib/lib'
make: *** [/home/SCHEME/scheme-lib/Makefile:54: lib/libvideo/libvideo.so] Error 2

**Comment by evilbinary** [comment]
@gassechen please install   `apt-get install liblz4-dev` first

**Comment by gassechen** [comment]
I have a ncurses 6 and fails compile. need install a ncuses 5? 
or edit a source file for link to ncuses 6? 
Entering directory '/home/SCHEME/scheme-lib/lib/scheme'
cc  -Wall -Wformat -I../libscm -g   main.o  -o scheme   -L../libscm -lscm -lm -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/ -ldl -lrt -lpthread -luuid -llz4 -L/usr/lib/x86_64-linux-gnu/
/usr/bin/ld: warning: libtinfo.so.5, needed by ../libscm/libscm.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ../libscm/libscm.so: undefined reference to `tputs@NCURSES_TINFO_5.0.19991023'
/usr/bin/ld: ../libscm/libscm.so: undefined reference to `cur_term@NCURSES_TINFO_5.0.19991023'
/usr/bin/ld: ../libscm/libscm.so: undefined reference to `setupterm@NCURSES_TINFO_5.0.19991023'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:64: scheme] Error 1
make[2]: Leaving directory '/home/SCHEME/scheme-lib/lib/scheme'
make[1]: *** [Makefile:55: scheme/scheme] Error 2
make[1]: Leaving directory '/home/SCHEME/scheme-lib/lib'
make: *** [Makefile:54: lib/libvideo/libvideo.so] Error 2

**Comment by evilbinary** [comment]
need install a ncuses 5 for libscm（from chezscheme）

**Comment by gassechen** [comment]
ok. its possible upgrade to ncurses 6? or chezscheme  work only with ncuses 5?

**Comment by evilbinary** [comment]
No time todo, u can user ncurses 6 later ,when it have done.But now just use ncuses 5.
